#!/usr/bin/env bash


SCRIPTFILE=$0

#Get the absolute path to the containing folder
PROJECTFOLDER=${SCRIPTFILE%/*}

cd ${PROJECTFOLDER}

pwd

pwd=$(pwd)

echo ""
echo --[CLEAN Folder]--------------------------------------------------------------------------
echo $pwd
echo ------------------------------------------------------------------------------------------
echo "
This script is will remove the bin, obj, and packages folder 
from $pwd" 
#echo "Continue? [y,n]"
#read answer
answer=y
echo ""

if [ "$answer" == "y" ] 
then 
    rm -R ./BoardPapers.Core/bin
    rm -R ./BoardPapers.Core/obj
    
    rm -R ./BoardPapers.Droid/bin
    rm -R ./BoardPapers.Droid/obj
    
    rm -R ./BoardPapers.iOS/bin
    rm -R ./BoardPapers.iOS/obj
    
    rm -R ./BoardPapers.UI/bin
    rm -R ./BoardPapers.UI/obj

    rm -R ./BoardPapers.UWP/bin
    rm -R ./BoardPapers.UWP/obj
    
    rm -R ./packages
fi
echo ------------------------------------------------------------------------------------------
echo ""